from typing import Dict


class BooksPort:
    async def get_book(self, book_id: str) -> Dict: ...
    async def mark_loaned(self, book_id: str) -> None: ...
    async def mark_returned(self, book_id: str) -> None: ...