from typing import Optional
from ..entities.loan import Loan


class LoansPort:
    async def save(self, loan: Loan) -> None: ...
    async def get(self, loan_id: str) -> Optional[Loan]: ...
    async def mark_returned(self, loan_id: str) -> None: ...